RELEASE_NOTES.md, src/Hocon.sln, src/core/Hocon.Tests/Hocon.Tests.csproj, src/core/Hocon.Tests/Properties/AssemblyInfo.cs, src/core/Hocon/Configuration/Config.cs, src/core/Hocon/Configuration/ConfigurationException.cs, src/core/Hocon/Configuration/ConfigurationFactory.cs, src/core/Hocon/Hocon.csproj, src/core/Hocon/Hocon/AkkaConfigurationSection.cs, src/core/Hocon/Hocon/CDataConfigurationElement.cs, src/core/Hocon/Hocon/HoconArray.cs, src/core/Hocon/Hocon/HoconConfigurationElement.cs, src/core/Hocon/Hocon/HoconLiteral.cs, src/core/Hocon/Hocon/HoconObject.cs, src/core/Hocon/Hocon/HoconParser.cs, src/core/Hocon/Hocon/HoconRoot.cs, src/core/Hocon/Hocon/HoconSubstitution.cs, src/core/Hocon/Hocon/HoconToken.cs, src/core/Hocon/Hocon/HoconTokenizer.cs, src/core/Hocon/Hocon/HoconValue.cs, src/core/Hocon/Hocon/IHoconElement.cs, src/core/Hocon/Properties/AssemblyInfo.cs, src/core/Hocon/packages.config, src/examples/HelloHocon/App.config, src/examples/HelloHocon/HelloHocon.csproj, src/examples/HelloHocon/Program.cs, src/examples/HelloHocon/Properties/AssemblyInfo.cs
- Bring over Hocon classes from akka.net project. No refactoring, straight
copy with some namespace changes. - structure is up for discussion
- Add Newtonsoft nuget package dependency
- Add Hocon.Tests Project.
- Create Examples solution folder
- Create HelloHocon example project with one sample in Program.cs
- Add RELEASE_NOTES.md
=> - Create initial project structure - up for discussion

src/core/Hocon.Tests/AssertionExtensions.cs, src/core/Hocon.Tests/ConfigurationSpec.cs, src/core/Hocon.Tests/Hocon.Tests.csproj, src/core/Hocon.Tests/HoconTests.cs, src/core/Hocon.Tests/packages.config
This PR includes the tests we had in the core Akka repo.
The test runner have been replaced with NUnit.
=> Added HOCON tests using NUnit

src/core/Hocon.Tests/Hocon.Tests.csproj, src/core/Hocon.Tests/HoconTests.cs, src/core/Hocon.Tests/packages.config, src/core/Hocon/Hocon/HoconArray.cs, src/core/Hocon/Hocon/HoconLiteral.cs, src/core/Hocon/Hocon/HoconObject.cs, src/core/Hocon/Hocon/HoconParser.cs, src/core/Hocon/Hocon/HoconTokenizer.cs
This PR tests the parser and tokenizer fault handling, and how we currently handle unspecified behaviors in the hocon spec
=> Added tests for invalid hocon and undefined hocon spec behaviors

.travis.yml
Merging this PR should be what we need to setup travis ci.
Resolves #11
=> - add .travis.yml to root folder.

src/core/Hocon/Configuration/ConfigurationFactory.cs
=> Add overload for Load() to specify a sectionName

.travis.yml, src/Hocon.sln, src/core/Hocon.Tests/Hocon.Tests.csproj, src/core/Hocon.Tests/Properties/AssemblyInfo.cs, src/core/Hocon/Akka.Hocon.csproj, src/core/Hocon/Configuration/ConfigurationException.cs, src/core/Hocon/Configuration/ConfigurationFactory.cs, src/core/Hocon/Configuration/Hocon/CDataConfigurationElement.cs, src/core/Hocon/Configuration/Hocon/HoconConfigurationElement.cs, src/core/Hocon/Configuration/Hocon/HoconConfigurationSection.cs, src/core/Hocon/Configuration/Hocon/HoconTokenizer.cs, src/core/Hocon/Properties/AssemblyInfo.cs, src/core/Hocon/packages.config
I see that @adamhathcock  also added support for Microsoft.Framework.Configuration in #28 . This should probably be added as well as a separate pull request.
I wasn't sure how your continuous integration system works with regards to how the nuget packages are built etc. This probably needs some tweaking since it changed in Visual Studio 2017.
=> Support for dotnetcore using new Visual Studio 2017 csproj format

src/HOCON.Tests/HoconTests.cs, src/HOCON/Parser.cs
Resolve https://github.com/akkadotnet/HOCON/issues/63
=> Fix unable to use include keyword at root level

build.fsx, build.ps1, build.sh, src/HOCON.Tests/Hocon.Tests.csproj, src/Hocon.Configuration.Test/ConfigurationSpec.cs, src/Hocon.Configuration.Test/Hocon.Configuration.Tests.csproj, src/Hocon.Extensions.Configuration.Tests/Hocon.Extensions.Configuration.Tests.csproj, src/common.props
Also fixed some of the test failures you were running into @Arkatufus
=> Modernized build system in preparation for Azure Pipelines migration

build-system/README.md, build-system/azure-pipeline.template.yaml, build-system/linux-pr-validation.yaml, build-system/windows-pr-validation.yaml, build-system/windows-release.yaml
Based on https://github.com/petabridge/petabridge-dotnet-new/releases/tag/0.5.1
=> added Azure Pipelines task definitions

src/Hocon.Tests/PathTests.cs
Add specific test for #79
Closes #79
=> Specific test for dot and comma in key

src/Hocon.Tests/ArrayAndObjectConcatenation.cs, src/Hocon.Tests/DuplicateKeysAndObjectMerging.cs, src/Hocon/Impl/HoconField.cs, src/Hocon/Impl/HoconSubstitution.cs
=> Object fields containing objects may not return proper object value in certain circumstances.

src/Hocon.Tests/SelfReferentialSubstitution.cs, src/Hocon/Impl/HoconObject.cs, src/Hocon/Parser.cs
=> Fix. Child field path was not concatenated with its parent path.

src/Hocon.Tests/ArrayAndObjectConcatenation.cs, src/Hocon.Tests/SelfReferentialSubstitution.cs, src/Hocon/Impl/HoconArray.cs, src/Hocon/Impl/HoconField.cs, src/Hocon/Impl/HoconMergedObject.cs, src/Hocon/Impl/HoconObject.cs, src/Hocon/Impl/HoconSubstitution.cs, src/Hocon/Impl/HoconValue.cs, src/Hocon/Impl/Utils.cs, src/Hocon/Parser.cs
Merge #99 and #101 into a single pull request.
Closes #99 and #101
=> Merge #99 and #101 into a single pull request.

src/Hocon/Impl/HoconValue.cs
=> Improve exception text when failed to parse TimeSpan value

build-system/linux-pr-validation.yaml
=> Revert "Update linux-pr-validation.yaml"

src/Hocon.Extensions.Configuration.Tests/ConfigurationSpec.cs
Added an `AwaitAssert`-like functionality to this spec to help harden it.
=> Fix racy ConfigReload spec

src/Hocon.Tests/HoconTests.cs
=> Added test for cyclic substitution loop error

src/Hocon.Extensions.Configuration/Hocon.Extensions.Configuration.csproj
Made this so @dependabot can update them more easily in the future.
=> simplify Microsoft.Extensions.Configuration dependencies

src/Hocon.Configuration/Hocon.Configuration.csproj, src/Hocon.Extensions.Configuration/Hocon.Extensions.Configuration.csproj, src/Hocon.Immutable/Hocon.Immutable.csproj, src/Hocon/Hocon.csproj, src/common.props
=> added proper <PackageDescription> tags for NuGet packages

src/Hocon.Tests/HoconTests.cs, src/Hocon/HoconRoot.cs
=> Add config getter defaults as in Akka.Configuration

src/Hocon.Tests/HoconTests.cs, src/Hocon/Impl/Exceptions/HoconValueException.cs, src/Hocon/Impl/HoconValue.cs
=> Updated HoconValue.AtKey implementation

build-system/nightly-builds.yaml
=> added nightly build definition.

src/Hocon.Configuration.Test/ConfigurationSpec.cs, src/Hocon.Configuration/Config.cs, src/Hocon/Extensions/HoconElementExtensions.cs, src/Hocon/Impl/HoconArray.cs, src/Hocon/Impl/HoconField.cs, src/Hocon/Impl/HoconObject.cs, src/Hocon/Impl/HoconSubstitution.cs, src/Hocon/Impl/HoconValue.cs, src/Hocon/Parser.cs
=> Fix Clone method to perform deep cloning, and made fallback immutable

src/Hocon.Configuration.Test/ConfigurationSpec.cs, src/Hocon.Tests/HoconTests.cs, src/Hocon/Impl/HoconObject.cs
=> Fixed merging of quoted keys with "invalid" characters

src/Hocon.Configuration.Test/DebuggerSpec.cs, src/Hocon.Configuration/Debugger/DebuggingExtensions.cs
Adds some helpful debugger tooling for viewing the fallback chain in HOCON.... But I've also used this PR to reproduce a bug that I'll file an issue for shortly.
=> HOCON Debugger tools

src/Hocon.Configuration/ConfigurationFactory.cs
=> make ConfigurationFactory.Load behavior backwards compatible

build.fsx, src/examples/SerializationDebug/SerializationDebug.csproj
Pushes `.snupkg` artifacts up to NuGet correctly
=> added symbol publishing support

src/Hocon.API.Tests/HoconAPISpec.ApproveConfiguration.approved.txt, src/Hocon.Benchmarks/LookupBenchmark.cs, src/Hocon.Benchmarks/ParserBenchmark.cs, src/Hocon.Configuration.Test/ConfigurationSpec.cs, src/Hocon.Configuration.Test/DebuggerSpec.cs, src/Hocon.Configuration.Test/SerializationSpecs.cs, src/Hocon.Configuration/Config.cs, src/Hocon.Configuration/HoconConfigurationFactory.cs, src/Hocon.Configuration/HoconConfigurationSection.cs, src/common.props, src/examples/Fallback/Program.cs, src/examples/HelloHocon/Program.cs, src/examples/SerializationDebug/Program.cs
Can't make another big breaking API change like this after going to 2.0 just a couple of weeks ago. API surface areas need to stay stable.
=> changed HoconConfigurationFactory back to ConfigurationFactory

src/Hocon.API.Tests/HoconAPISpec.ApproveConfiguration.approved.txt, src/Hocon.Benchmarks/LookupBenchmark.cs, src/Hocon.Benchmarks/ParserBenchmark.cs, src/Hocon.Configuration.Test/ConfigurationSpec.cs, src/Hocon.Configuration.Test/DebuggerSpec.cs, src/Hocon.Configuration.Test/SerializationSpecs.cs, src/Hocon.Configuration/Config.cs, src/Hocon.Configuration/HoconConfigurationFactory.cs, src/Hocon.Configuration/HoconConfigurationSection.cs, src/common.props, src/examples/Fallback/Program.cs, src/examples/HelloHocon/Program.cs, src/examples/SerializationDebug/Program.cs
=> Revert "changed HoconConfigurationFactory back to ConfigurationFactory"

.gitignore, Hocon.sln, build-system/linux-pr-validation.yaml, build-system/windows-pr-validation.yaml, build-system/windows-release.yaml, build.fsx, src/Hocon.Tests.Performance/ConfigLookupSpec.cs, src/Hocon.Tests.Performance/Hocon.Tests.Performance.csproj, src/Hocon.Tests.Performance/Program.cs
Add NBench performance benchmarks, closes #200
Taken from https://github.com/akkadotnet/HOCON/pull/231
=> Add NBench perf spec
