akkadotnet/HOCON

src/core/Hocon/Hocon.csproj
src/core/Hocon/Hocon/HoconParser.cs
src/core/Hocon/Hocon/HoconParserException.cs
src/core/Hocon/Hocon/HoconToken.cs
src/core/Hocon/Hocon/HoconTokenizer.cs
src/core/Hocon/Hocon/HoconTokenizerException.cs

This PR adds significantly better exception information when a parser problem occurs.
Instead of just throwing and reporting that something broke, we now report where the source text and where in the HOCON tree the problem occured, 
In the screenshot this hocon was used:
```javascript
root {
some-property1 = [ 
some-property2 = 234     ///"some-property" was added to the array as an unquoted string and "= 234" was considered an unknown token.
}
```
cc @nvivo you wanted better error reporting on hocon, any feedback on how to improve this even more would be great
Related to #13

Exceptions diagnostics

---

build.fsx

The Newtonsoft dependency wasn't added during the build process. 
I also removed the ```project``` argument from ```getAkkaDependency``` because it is not used... 
Regards
Marc

Added dependencies to the nuget file

---

src/HOCON.Tests/HoconTests.cs
src/HOCON/Config.cs
src/HOCON/Hocon.csproj
src/HOCON/Impl/HoconParser.cs
src/HOCON/Impl/HoconSubstitution.cs
src/HOCON/Impl/HoconTokenizer.cs
src/HOCON/Impl/HoconValue.cs

Related issues: #14 #40 
Add ${? Hocon feature:
- Fallback to environment variable if substitution is unresolved
- Fails silently and removes unresolved field or substituted array items if substitution is unresolved completely
NOTE:  Project moved to standard1.3 for Environment.GetEnvironmentVariable() support

Substitution ${? features

---

src/Hocon.Benchmarks/Hocon.Benchmarks.csproj
src/common.props

Just needed to add the `<IsPackable>false</IsPackable>` to stop NuGet packages from being released for the HOCON benchmarks

removed Hocon.Benchmarks nuget package

---

src/HOCON.Tests/DuplicateKeysAndObjectMerging.cs
src/HOCON.Tests/PathTests.cs
src/HOCON/Impl/HoconObject.cs
src/HOCON/Impl/HoconPath.cs
src/HOCON/Impl/Utils.cs

This is an attempt at addressing issue #71 
The bug is caused by attempting to add a new key to a merged object, which is not the same as the field's actual underlying value.

fixed bug where dot notation doesn't work properly

---

src/Hocon.Tests/ArrayAndObjectConcatenation.cs

This test case will be failed when run on windows.

Fix a windows EOL bug for test case

---

.gitignore
src/Hocon.Extensions.Configuration.Tests/Hocon.Extensions.Configuration.Tests.csproj
src/examples/Fallback/Program.cs
src/examples/Fallback/Properties/launchSettings.json

Add a simple environment variable substitution fallback sample to the Fallback sample project.
For debug mode, MY_ENV_PROPERTY is set inside the project properties under Debug tab.
For release mode, the user have to set the environment variable themselves before running the console app.

Substitution environment variable fallback sample

---

src/Hocon.Configuration/Config.cs
src/Hocon/HoconRoot.cs
src/Hocon/Impl/HoconField.cs
src/Hocon/Impl/HoconObject.cs
src/Hocon/Impl/HoconValue.cs

Removed HoconValue.Undefined, will be replaced with nullable reference when we move to C# 8.0

HoconValue.Undefined is inconsistent

---

RELEASE_NOTES.md
src/common.props

HOCON 1.1.0 contains a large number of bug fixes and improvements over HOCON 1.0.0, including:
* [Fix: fully qualified type name with assembly cant be used as property name ](https://github.com/akkadotnet/HOCON/issues/79)
* [Fix: unable to use include keyword at root level](https://github.com/akkadotnet/HOCON/pull/69)
* [Fix. Child field path was not concatenated with its parent path](https://github.com/akkadotnet/HOCON/pull/96)
* [Fix: bug when getting a string with a substitution as an array element](https://github.com/akkadotnet/HOCON/pull/88)
* [Fix: Object fields containing objects may not return proper object value in certain circumstances. ](https://github.com/akkadotnet/HOCON/pull/93)
* [Fix: Improper value instantiation and parenting during parsing caused a disconnected tree …

added 1.1.0 HOCON release notes

---

src/Hocon.Tests/HoconTests.cs
src/Hocon/Impl/HoconObject.cs

Close #125 
So, here is the issue: during parsing of hocon object, we need to store object's keys. And with double-quoted keys, if we will include `'"'` sign in the key, we will not be able to make requests like `config.GetInt("a")` if `a` was double-quoted. Or, if we will omit `'"'` sign when storing the key ) which looks better, and this is what we are doing) - we will loose information that this key was double-quoted.
This information is not that important - until we will try to get value from object by it's path. That is exactly what happens when we call `config.GetObject("A")` for example - recursively it will iterate children, using keys of the object like hocon paths.
And guess what - for double-quoted key "X.Y" we have hocon path "X.Y" (we do not know that is was double-quoted, so …

Fix parsing of quoted keys

---

src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration.Test/Hocon.Configuration.Tests.csproj
src/Hocon/Extensions/HoconElementExtensions.cs
src/Hocon/Impl/HoconObject.cs
src/Hocon/Impl/HoconValue.cs
src/Hocon/Parser.cs

Close #127 
The basic idea of the fix is that in current implementation substitution takes value "by reference" - which means that when object merge occurs the initial value, referenced in substitution, is modified. This could lead to lots of issues, not only with the once described in closing issue.
So the fix is basically make substitution to just deeply copy referenced sub-tree, so that it was safe to modify.
In the edge case when we do not need to modify referenced object we could still keep the "be reference" behavior instead of "by value". Not sure if it will save much performance and if it is important at all. But checking if we are somehow, somewhere modifying substituted value (not to say that we could reference one sub-tree, that includes another substitution that could also be …

Fixed merge for substitutions

---

src/Hocon.Tests/DuplicateKeysAndObjectMerging.cs
src/Hocon.Tests/Hocon.Tests.csproj
src/Hocon/Parser.cs

Close #137 
While debugging, it turned out that what current implementation does is taking value by key (create if not exists) and append array values to it.
So, actually, the following:
```
c: {
a: [2. 3]
b: [4]
a: [5]
}
```
was ending up with `a = [2, 3, 5]`. So, arrays with same paths were always concatenating, as if one was continuation of another.
And as far as I understand the specs, the only case when arrays are concatenated is when they are separated with non-newline while space. From README:
```
Within an field value or array element, if only non-newline white-space separates the end of a first array or object or substitution from the start of a second array or object or substitution, the two values are concatenated.
```
So for me, this is a special case that should be explicitly …

Fix arrays merge

---

src/Hocon.Tests/HoconTests.cs
src/Hocon.Tests/SelfReferentialSubstitution.cs
src/Hocon/Impl/HoconField.cs

Close #123
The problem here was that when setting value to some object's key, we were deleting all substitutions from the old value - even if the same substitutions were used in new value. 
Also, noticed that rewriting value was used only for literals. I.e. 
```
foo = ${not-exists}
foo = [42]
```
was failing, since it did not allow arrays to overwrite values. Which is of course a bug. Fixed as it was almost in the same line.

Fix removing substitutions that are still to be resolved

---

README.md
src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration.Test/Hocon.Configuration.Tests.csproj
src/Hocon.Configuration.Test/app.conf
src/Hocon.Configuration/ConfigurationFactory.cs

closes #151
Added ConfigurationFactory.FromFile method
Added new HOCON loading order per 151
Made ConfigurationFactory.Load Obsolete

add default HOCON loading methods (#151)

---

RELEASE_NOTES.md
src/common.props

HOCON 1.2.1 contains many minor bug fixes and behavioral changes.
**Default HOCON loading order**
Per [issue 151](https://github.com/akkadotnet/HOCON/issues/151), `HOCON.Configuration` now looks for default HOCON content in the following places in the following order:
1. [.NET Core / .NET Framework] An "app.conf" or an "app.hocon" file in the current working directory of the executable when it loads;
2. [.NET Framework] - the `<hocon>` `ConfigurationSection` inside `App.config` or `Web.config`, which should also resolve #8 and #9 
3. [.NET Framework] - and a legacy option, to load the old `<akka>` HOCON section for backwards compatibility purposes with all users who have been using HOCON with Akka.NET.
**Bug fixes**:
For a set of complete bug fixes and changes, please see [the HOCON …

added v1.2.1 release notes

---

src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration/Config.cs

Close #161
Just added overload for `config.ToString()` method, that would allow to dump all fallback values.

Add config.ToString(bool useFallbackValues) overload to include fallback values

---

RELEASE_NOTES.md
src/common.props

HOCON 1.3.0 contains some significant API changes:
* [API parity with pre-existing Akka.NET HOCON implementation](https://github.com/akkadotnet/HOCON/issues/157)
* Added `HoconType.String`, `HoconType.Number`, `HoconType.Bool`, and removed `HoconType.Literal` - now it's possible to discover data types more easily while inspecting individual HOCON objects.
* [Fixed: Need to be able to include Config fallback values to string representation](https://github.com/akkadotnet/HOCON/issues/161)
* [Added SourceLink.Github support](https://github.com/akkadotnet/HOCON/pull/166)
For a set of complete bug fixes and changes, please see [the HOCON v1.3.0 milestone on Github](https://github.com/akkadotnet/HOCON/milestone/3).

added v1.3.0 release notes

---

src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration/Config.cs

Close #177
The issue turned out to be little bit deeper then I thought at start.
Assuming that `config` has fallback values, `config.Root.GetObject()` returns object not containing fallback values because `Root` property of type `HoconValue` does not contain them.
Hocon core library does not work with fallbacks in any way - so `HoconValue` does not have any information about possible fallbacks it has.
So the way to go is to aggregate all fallback values into Root property, which is what I am doing. Since `HoconValue` type is mutable, making separate value and putting values in reverse order - to support proper fallbacks ordering when hocon will merge inner objects.
Also, seems like few more functions in `Config` file were trying to check if any fallbacks exist - there is no need to do …

Config.Root should contain fallback values 

---

RELEASE_NOTES.md
src/common.props

**Bugfix release for HOCON v1.3.0**
You can [see the full set of changes in the HOCON v1.3.1 milestone](https://github.com/akkadotnet/HOCON/milestone/4).

added v1.3.1 release notes

---

src/HOCON.Tests/QuotedString.cs
src/Hocon/Impl/HoconField.cs
src/Hocon/Impl/IHoconElement.cs

fix string unquoting upon parse

---

src/Hocon.Configuration.Test/DebuggerSpec.cs
src/Hocon.Configuration/Config.cs

Do not mutate config.Fallback values when building Root property

---

RELEASE_NOTES.md
src/common.props

**Bugfix release for HOCON v1.3.0**
Key changes include:
* [Critical bugfix: Fallbacks are mutable during traversal](https://github.com/akkadotnet/HOCON/issues/193)
* [Added HOCON Debugger tools](https://github.com/akkadotnet/HOCON/pull/192)
* [Performance: Lookups on configs with fallback are performing merge and allocations each time](https://github.com/akkadotnet/HOCON/issues/195)
You can [see the full set of changes in the HOCON v1.3.2 milestone](https://github.com/akkadotnet/HOCON/milestone/5).

added v1.3.2 release notes

---

RELEASE_NOTES.md
src/HOCON.Tests/QuotedString.cs
src/Hocon.Configuration.Test/DebuggerSpec.cs
src/Hocon.Configuration/Config.cs
src/Hocon.Configuration/ConfigurationFactory.cs
src/Hocon.Configuration/Debugger/DebuggingExtensions.cs
src/Hocon/Impl/HoconField.cs
src/Hocon/Impl/IHoconElement.cs
src/common.props

**Bugfix release for HOCON v1.3.0**
Key changes include:
* [Critical bugfix: Fallbacks are mutable during traversal](https://github.com/akkadotnet/HOCON/issues/193)
* [Added HOCON Debugger tools](https://github.com/akkadotnet/HOCON/pull/192)
* [Performance: Lookups on configs with fallback are performing merge and allocations each time](https://github.com/akkadotnet/HOCON/issues/195)
You can [see the full set of changes in the HOCON v1.3.2 milestone](https://github.com/akkadotnet/HOCON/milestone/5).

v1.3.2 Release

---

src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration/Config.cs

Close #206
Fairly talking, this is a quick fix: when serializing config, we are producing something like `{ "_dump": "<config.ToString()>" }` - but at least this is a valid json, and correctly deserializable.
The only thing this will break if people for some reason are storing HOCON configuration in json format, and then will try to load their stored configuration with our new library version. But that's edge (and weird) case, so let's have this as a quick fix.

Support Config serialization with ISerializable

---

Hocon.sln
src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration.Test/DebuggerSpec.cs
src/Hocon.Configuration.Test/SerializationSpecs.cs
src/Hocon.Configuration/Config.cs
src/Hocon.Configuration/ConfigurationFactory.cs
src/Hocon.Configuration/DebuggingExtensions.cs
src/common.props
src/examples/SerializationDebug/Program.cs
src/examples/SerializationDebug/SerializationDebug.csproj

moved DebuggingExtensions into default Hocon namespace to make it easier to use in Visual Studio immediate Window

Akka.NET compatibility fixes

---

RELEASE_NOTES.md
src/common.props

**Bugfix release for HOCON v1.3.0**
Key changes include:
* [Make `Config` implement `ISerializable`](https://github.com/akkadotnet/HOCON/pull/207)
* [Implement Akka.NET backwards compatibility fixes](https://github.com/akkadotnet/HOCON/pull/204)
You can [see the full set of changes in the HOCON v1.3.3 milestone](https://github.com/akkadotnet/HOCON/milestone/6).

added v1.3.3 release notes

---

src/Hocon.Configuration.Test/SerializationSpecs.cs
src/Hocon.Configuration/Config.cs
src/Hocon.Configuration/ConfigurationFactory.cs
src/Hocon/HoconRoot.cs

- Make serialization work using `ISerializable`
- Resolve `Config` containing a single empty object as an empty `Config`

Fix Config serialization and empty Config serialization.

---

src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration/Config.cs
src/Hocon.Configuration/ConfigurationException.cs
src/Hocon.Configuration/HoconConfigurationSection.cs
src/Hocon.Tests/HoconTests.cs
src/Hocon/HoconRoot.cs
src/Hocon/Impl/HoconObject.cs
src/Hocon/Impl/HoconPath.cs
src/Hocon/Impl/HoconValue.cs

Still related to https://github.com/akkadotnet/akka.net/pull/4128
- Add `IEquitable<Config>` interface implementation to `Config` class
- `GetString()`, `GetStringList()`, `GetInt()`, and `GetDouble()` throws on failure instead of returning a default value (Major change in Akka.NET).
- Add `TryGet[DataType]()` functions to all getters to eliminate as much Exception throwing as possible to improve performance.
- Remove as much wrapping functions as possible to improve performance.
- Move ConfigurationException from Akka.Configuration to Hocon
- Fix Config.WithFallback() with hocon files containing substitution failed to merge the fallbacks correctly.

Hocon improvement.

---

Hocon.sln
build.fsx
src/Hocon.API.Tests/Hocon.API.Tests.csproj
src/Hocon.API.Tests/HoconAPISpec.ApproveConfiguration.approved.txt
src/Hocon.API.Tests/HoconAPISpec.ApproveCore.approved.txt
src/Hocon.API.Tests/HoconAPISpec.ApproveExtensionConfiguration.approved.txt
src/Hocon.API.Tests/HoconAPISpec.ApproveImmutable.approved.txt
src/Hocon.API.Tests/HoconAPISpec.cs
src/Hocon.API.Tests/HoconAPISpecConfig.cs
src/Hocon.Benchmarks/LookupBenchmark.cs
src/Hocon.Benchmarks/ParserBenchmark.cs
src/Hocon.Configuration.Test/ConfigurationSpec.cs
src/Hocon.Configuration.Test/DebuggerSpec.cs
src/Hocon.Configuration.Test/SerializationSpecs.cs
src/Hocon.Configuration/Config.cs
src/Hocon.Configuration/HoconConfigurationFactory.cs
src/Hocon.Configuration/HoconConfigurationSection.cs
src/Hocon.Extensions.Configuration/HoconConfigurationFileParser.cs
src/Hocon/Impl/HoconArray.cs
src/Hocon/Impl/HoconEmptyValue.cs
src/Hocon/Impl/HoconField.cs
src/Hocon/Impl/HoconLiteral.cs
src/Hocon/Impl/HoconObject.cs
src/Hocon/Impl/HoconSubstitution.cs
src/Hocon/Impl/HoconValue.cs
src/Hocon/Impl/IHoconElement.cs
src/examples/Fallback/Program.cs
src/examples/HelloHocon/Program.cs
src/examples/SerializationDebug/Program.cs

Add API test using ApiApproval

Add API test project.

---

src/Hocon.Configuration.Test/SerializationSpecs.cs
src/Hocon.Configuration/ConfigurationFactory.cs
src/Hocon.Tests/PathTests.cs
src/Hocon/Impl/HoconObject.cs

Keys with invalid characters such as period and angle braces are not serialized within quotation marks.

Fix unquoted key error during serialization.

---

src/common.props

fixed NuGet symbol publishing

---

src/Hocon.API.Tests/HoconAPISpec.ApproveConfiguration.approved.txt
src/Hocon.Configuration.Test/ConcurrentImmutablitySpec.cs
src/Hocon.Configuration/Config.cs

Closes #233
Bug was caused by multiple threads accessing the `Config.Root` property and `Config.Root` was not thread-safe.

Fix for #233: TryGetObject threws.

---

RELEASE_NOTES.md
src/common.props

Bugfixes and improvements made to HOCON 2.0.0
* [Bugfix: HoconValue.TryGetObject can throw System.ArgumentNullException](https://github.com/akkadotnet/HOCON/issues/233)
* [Bugfix: System.InvalidOperationException : Collection was modified; enumeration operation may not execute](https://github.com/akkadotnet/HOCON/issues/234)
* [Bugfix: unquoted key error during serialization](https://github.com/akkadotnet/HOCON/pull/223)
* [Fixed NuGet symbol package publication](https://github.com/akkadotnet/HOCON/issues/222)
For more details, please [see the issues in the HOCON v2.0.1 milestone here](https://github.com/akkadotnet/HOCON/milestone/7).

add v2.0.1 release notes

---

RELEASE_NOTES.md
src/common.props

HOCON 2.0.2 contains a final stabilization of the HOCON 2.0 milestone, designed to provide 100% immutability to HOCON objects and high performance on reads.
See [the HOCON 2.0.2 milestone for a full set of changes](https://github.com/akkadotnet/HOCON/milestone/8).

HOCON v2.0.2 Release Notes

---

src/Hocon.Configuration/HoconConfigurationFactory.cs

Closes https://github.com/akkadotnet/HOCON/issues/159
Change the default file load priority to (in order, from top to bottom):
- application.conf
- application.hocon
- application.properties
- app.conf
- app.hocon
- app.properties

Change the default file names and load priority
